### ISSUE TITLE
error: unexpected remote arg

### ISSUE THREAD

**Issue by martin2250** [socratesx/myrsync#5]
Hi Socrates,

I've started using myRSync, but it works pretty unreliably.
Almost every time I've tried to run the configuration, this error appeared: [https://pastebin.com/5n07dMWV](https://pastebin.com/5n07dMWV)
the funny thing is that it worked perfectly for a single time (neither the first or last time that I tried).

my configuration:
![Screenshot](https://user-images.githubusercontent.com/8293473/57984207-d3774d80-7a59-11e9-8a5f-fadf4c124e7d.png)

this results in the command
`rsync -rvt -h --delete  rsync://martin@192.168.2.186:873/music /storage/emulated/0/Music`

**Comment by socratesx** [comment]
Hi

I was able to replicate the problem using your configuration. There is a bug apparently with the rsync pull mode. I will have to check it and fix it. When I do I will report back.

Thank you for your feedback. It is really helpful in order to make the app stable.

Best Regards,
Socrates

-------- Original Message --------

**Comment by socratesx** [comment]
Hi Martin

Can you please check If this issue is resolved as well? 

Thanks
Socrates

**Comment by martin2250** [comment]
Hi Socrates,

it seems to work reliably now. Thanks!

Martin
